#theme: jekyll-theme-minimal
#title: Absent Service's Github Page
#description: Bookmark this to keep an eye on my project updates!

title: Absent Service's Github Page
tagline: tagline
description: Come check out our projects
show_downloads: false #["true" or "false" (unquoted) to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
